### ISSUE TITLE
Feature request: order on VertexQuery

### ISSUE THREAD

**Issue by sipi** [tinkerpop/blueprints#523]
Hi,
I would like a feature like .order(String key) and .orderDesc(String key) on VertexQuery or GraphQuery.
Is there a reason why it is missing? Or, is it just not yet implemented?

Thanks

**Comment by spmallette** [comment]
We will not be changing the Blueprints API as the 2.x line of code is basically in maintenance mode as we are full speed ahead on TinkerPop3:

http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/

I suspect this issue is resolved by the API changes there:

http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#order-step

**Comment by sipi** [comment]
Perfect, I wait for the version 3.0.

Thanks.
